### ISSUE TITLE
Autogenerated PDF file do not have correct page numbers

### ISSUE THREAD

**Issue by RexTheCapt** [jarleven/VG3DENetworkConnection#9]
The script build.sh creates generates the PDF file that is the entire documentation but it has a little error in it.

The page numbers are not correct at all. The first 3 pages is correctly numbered but everything else after that is just page 1 and that might be a little problem later on.

**Comment by jarleven** [comment]
Can be fixed by appending the .md files together instead of the pdf files.
Some discussion of the linebreak here : https://stackoverflow.com/questions/16965490/pandoc-markdown-page-break
And the sed command to insert someting at the top of the file: https://superuser.com/questions/246837/how-do-i-add-text-to-the-beginning-of-a-file-in-bash

Briefly tested this and it seems to work. Need to modify the makedoc.sh accordingly.

## Loops through files  add a LaTex pagebreak at the top of all the tables
for filename in ./*.md
do
sed -i '1s/^/\\pagebreak\n/' $filename

done


cat *.md > test.md

pandoc -f markdown  -s -o test.pdf test.md

**Comment by jarleven** [comment]
https://github.com/RexTheCapt/VG3DENetworkConnection/blob/master/makedoc_v2.sh
Use this as an example.

**Comment by RexTheCapt** [comment]
@jarleven why not integrate it into the main file?
